feat/user-login-aabha
tech-university-india/uhi-authentication pull request #1
Opened 2023-02-11 07:43 UTC by xentro-sam

2023-02-11 14:55 UTC, Saatwik-S approved these changes

2023-02-12 05:25 UTC, rkdixit96 requested changes

2023-02-12 05:25 UTC, rkdixit96 commented on src/util/abdm/userOnboardingApi.js
> +}
Move urls to config file

2023-02-12 05:25 UTC, rkdixit96 commented on src/util/abdm/publicKeyFetcher.js
> +}
This is a service

2023-02-12 05:25 UTC, rkdixit96 commented on src/util/abdm/authToken.js
> +const getJWTToken = async () => {
This is a service

2023-02-12 05:25 UTC, rkdixit96 commented on src/util/abdm/authToken.js
> +const fetchJWTFromServer = async () => {
This is a service

2023-02-12 05:26 UTC, rkdixit96 commented
Lets move to use axios redis cache adapter for storing tokens - https://www.npmjs.com/package/axios-cache-adapter.
We'll do this in a separate PR

2023-02-13 06:10 UTC, xentro-sam commented
Requested changes made. Kindly approve PR.

2023-02-13 14:36 UTC, rkdixit96 approved these changes

2023-02-13 14:36 UTC, merged