Feat/forgot abha number
tech-university-india/uhi-authentication pull request #16
Opened 2023-03-16 07:22 UTC by yashasva01

2023-03-16 08:14 UTC, souris-dev requested changes

2023-03-16 08:14 UTC, souris-dev commented on src/routes/retrieveAbhaRoutes.js
> +  validator.validate(validator.schemas.checkAbhaexistsService, validator.REQ_PARAMTERS.body),
nit: Let's use camel case - `checkAbhaExistsService`

2023-03-16 08:14 UTC, souris-dev commented on src/services/retrieveAbhaServices.js
> +async function checkAbhaexistsService (healthId) {
nit: Let's use camel case - checkAbhaExistsService

2023-03-16 08:14 UTC, souris-dev commented on src/util/middleware/validator.js
> +  checkAbhaexistsService: joi.object({
nit: Let's use camel case - checkAbhaExistsService

2023-03-16 12:01 UTC, souris-dev approved these changes

2023-03-17 07:35 UTC, yashasva01 commented on src/routes/retrieveAbhaRoutes.js
> +  validator.validate(validator.schemas.checkAbhaexistsService, validator.REQ_PARAMTERS.body),
done

2023-03-17 07:36 UTC, yashasva01 commented on src/services/retrieveAbhaServices.js
> +async function checkAbhaexistsService (healthId) {
done

2023-03-20 09:09 UTC, SaatwikRishi approved these changes

2023-03-20 09:09 UTC, merged