Feat/delete user account
tech-university-india/uhi-authentication pull request #18
Opened 2023-03-16 10:13 UTC by shreyas1925

1. generate otp and verify otp using mobile number working.
2. generate otp working for aadhaar , verify otp throwing 500 error.

2023-03-16 10:30 UTC, ishit-007 approved these changes

2023-03-16 10:46 UTC, souris-dev requested changes

2023-03-16 10:46 UTC, souris-dev commented on package.json
> +    "nodemon": "^2.0.21",
Let's make nodemon a devDependency

2023-03-16 10:46 UTC, souris-dev commented on src/controllers/deleteAccount.js
> +            // not working
// TODO: govt endpoint not working

2023-03-16 10:46 UTC, souris-dev commented on src/services/abdm/delete/aadhar.js
> +    console.log("data2",data);
Let's remove this

2023-03-16 10:46 UTC, souris-dev commented on src/services/abdm/delete/aadhar.js
> +    console.log("hello");
Let's remove this console.log

2023-03-16 10:46 UTC, souris-dev commented on src/services/abdm/delete/phone.js
> +    console.log("data2",data);
Let's remove this console.log

2023-03-20 08:35 UTC, SaatwikRishi approved these changes

2023-03-20 08:42 UTC, SaatwikRishi approved these changes

2023-03-20 08:44 UTC, merged