Onboard users
tech-university-india/uhi-authentication pull request #5
Opened 2023-03-05 06:48 UTC by maitra100

2023-03-06 16:35 UTC, rkdixit96 requested changes

2023-03-06 16:35 UTC, rkdixit96 commented on src/controllers/addUser.js
> +module.exports = addUserController
rename to just user.js

2023-03-06 16:35 UTC, rkdixit96 commented on src/services/addUser.js
> +  }, { returning: true })
Just spread the userObject inside create 
```
db.Users.create({
    ...user
}
```

2023-03-06 16:35 UTC, rkdixit96 commented on database/migrations/20230304175042-changeGender.js
> +}
Combine all these migrations into one migration

2023-03-06 18:21 UTC, maitra100 commented on src/controllers/addUser.js
> +module.exports = addUserController
done

2023-03-06 18:21 UTC, maitra100 commented on src/services/addUser.js
> +  }, { returning: true })
done

2023-03-06 18:21 UTC, maitra100 commented on database/migrations/20230304175042-changeGender.js
> +}
done

2023-03-07 04:07 UTC, rkdixit96 requested changes

2023-03-07 04:07 UTC, rkdixit96 commented on src/util/middleware/userOnboardingValidator.js
> +const userValidator = (req, res, next) => {
Create generic validator that accepts schema as input

2023-03-07 04:07 UTC, rkdixit96 commented on src/routes/user.js
> +module.exports = router1
Please don't use variables like `router1`. Just call them router

2023-03-07 04:07 UTC, rkdixit96 commented on src/database/models/users.js
> +    modelName: 'Users'
Tables - use all small letters

2023-03-07 13:52 UTC, maitra100 commented on src/routes/user.js
> +module.exports = router1
done

2023-03-07 13:52 UTC, maitra100 commented on src/database/models/users.js
> +    modelName: 'Users'
done

2023-03-07 14:26 UTC, maitra100 commented on src/util/middleware/userOnboardingValidator.js
> +const userValidator = (req, res, next) => {
done

2023-03-08 04:53 UTC, rkdixit96 approved these changes

2023-03-13 06:11 UTC, SaatwikRishi approved these changes

2023-03-13 06:12 UTC, merged